apiVersion: v1
kind: Service
metadata:
  name: springboot-discovery-test-gateway
  namespace: dev
spec:
  ports:
    - port: 15001
      name: springboot-discovery-test-gateway
      nodePort: 31000
  type: NodePort
  selector:
    app: springboot-discovery-test-gateway

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-discovery-test-gateway
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-discovery-test-gateway
  template:
    metadata:
      labels:
        app: springboot-discovery-test-gateway
    spec:
      containers:
        - name: springboot-discovery-test-gateway
          image: springboot-discovery-test-gateway:1.0.0
#           env:
#            - name: JVM_ARGS
#              value: -Xms512m -Xmx512m -Dmetadata.version=stable
          ports:
            - protocol: TCP
              containerPort: 15001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-discovery-test-service-a
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-discovery-test-service-a
  template:
    metadata:
      labels:
        app: springboot-discovery-test-service-a
    spec:
      containers:
        - name: springboot-discovery-test-service-a
          image: springboot-discovery-test-service-a:1.0.0
#           env:
#            - name: JVM_ARGS
#              value: -Xms512m -Xmx512m -Dmetadata.version=stable
          ports:
            - protocol: TCP
              containerPort: 13001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-discovery-test-service-b
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-discovery-test-service-b
  template:
    metadata:
      labels:
        app: springboot-discovery-test-service-b
    spec:
      containers:
        - name: springboot-discovery-test-service-b
          image: springboot-discovery-test-service-b:1.0.0
#           env:
#            - name: JVM_ARGS
#              value: -Xms512m -Xmx512m -Dmetadata.version=stable
          ports:
            - protocol: TCP
              containerPort: 14001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-discovery-test-service-c
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-discovery-test-service-c
  template:
    metadata:
      labels:
        app: springboot-discovery-test-service-c
    spec:
      containers:
        - name: springboot-discovery-test-service-c
          image: springboot-discovery-test-service-c:1.0.0
#           env:
#            - name: JVM_ARGS
#              value: -Xms512m -Xmx512m -Dmetadata.version=stable
          ports:
            - protocol: TCP
              containerPort: 16001

