
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-discovery-test-service-a-feature11
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-discovery-test-service-a-feature11
  template:
    metadata:
      labels:
        app: springboot-discovery-test-service-a-feature11
    spec:
      containers:
        - name: springboot-discovery-test-service-a-feature11
          image: springboot-discovery-test-service-a:feature-1.1
          env:
           - name: JVM_ARGS
             value: -Xms512m -Xmx512m -Dmetadata.version=feature-1.1
          ports:
            - protocol: TCP
              containerPort: 13001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-discovery-test-service-c-feature11
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-discovery-test-service-c-feature11
  template:
    metadata:
      labels:
        app: springboot-discovery-test-service-c-feature11
    spec:
      containers:
        - name: springboot-discovery-test-service-c-feature11
          image: springboot-discovery-test-service-c:feature-1.1
          env:
           - name: JVM_ARGS
             value: -Xms512m -Xmx512m -Dmetadata.version=feature-1.1
          ports:
            - protocol: TCP
              containerPort: 16001

